@baseUrl = http://localhost:4001/api/v1

### 0. Register New User
# @name registerUser
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username": "jamine_tester",
    "email": "tester@example.com",
    "password": "password123",
    "confirmPassword": "password123"
}

### 1. Login Normal User
# @name userLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "tester@example.com",
    "password": "password123"
}

### 2. Get My Profile (ดูโปรไฟล์ตัวเอง)
GET {{baseUrl}}/users/me

### 3. Update My Profile
@userId = {{userLogin.response.body.data._id}}
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "username": "jamine_updated_user"
}

### 4. Logout
POST {{baseUrl}}/users/logout
